spring:
  profiles:
    active: dev

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml


